---
- hosts: web
  gather_facts: yes

  tasks:
    - name: get ip address
      debug:
        msg: "{{ ansible_all_ipv4_addresses }}"
    - name: get ip address 2
      debug:
        msg: "{{ ansible_ens160.ipv4.address }}"
